CREATE APPLICATION ROLE APP_PUBLIC;
CREATE SCHEMA IF NOT EXISTS CORE;
GRANT USAGE ON SCHEMA CORE TO APPLICATION ROLE APP_PUBLIC;

-- create table that will store the mappings
CREATE TABLE IF NOT EXISTS CORE.BUSINESS_MAPPING_TABLE (
  Oppty_GCoE_Branch_Type varchar, 
  Oppty_GCoE_Case_Owner_CoEBranch varchar
);
-- grant select privilege on the mapping table to the consumer
GRANT SELECT ON TABLE CORE.BUSINESS_MAPPING_TABLE TO APPLICATION ROLE APP_PUBLIC;
-- insert some sample data
INSERT INTO CORE.BUSINESS_MAPPING_TABLE VALUES('Direct', 'APAC - India CoE');

CREATE STREAMLIT CORE.BUSINESS_MAPPING_ST
  FROM '/streamlit'
  MAIN_FILE = '/business_mapping_st.py';
GRANT USAGE ON STREAMLIT CORE.BUSINESS_MAPPING_ST TO APPLICATION ROLE APP_PUBLIC;